language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

before_script:
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --dev --prefer-source

script:
 - phpunit --coverage-text

notifications:
  email: flame1980@gmail.com
